Add StarterProjectHealthMetricsModel
oss-compass/compass-metrics-model pull request #18
Opened 2023-02-28 08:53 UTC by lishengbao

2023-02-28 09:01 UTC, eyehwan commented
https://github.com/oss-compass/community/issues/10

2023-02-28 09:16 UTC, eyehwan reviewed
with some minor comments.

2023-04-18 08:58 UTC, lishengbao commented on run.py
> +   kwargs = {}
done.

2023-04-19 01:44 UTC, eyehwan requested changes

2023-04-19 01:44 UTC, eyehwan commented on compass_metrics_model/metrics_model_lab.py
> +def is_bot_by_author_name(*author_name):
1. This part should not hard code here, prefer adding an extra config file to record all bot account. 
2. Except for full name of bot, also need to consider pattern, like **bot, to filter out bot.

2023-04-20 07:23 UTC, eyehwan commented
I will merge first.

2023-04-20 07:23 UTC, merged